services:
  flask:
    build: .
    ports:
      - "5004:5004"
    volumes:
      - .:/app
    expose:
      - "5004"
    networks:
      - mlops-networks

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    depends_on:
      - flask
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - mlops-networks

networks:
  mlops-networks:
    driver: bridge